const colors = {
  dark: {
    tabBar: "#1c1b1a",
    background: "#424549",
    tabFocused: "white",
    tabUnfocused: "grey",
    thumbColorTrue: "white",
    thumbColorFalse: "white",
    trackColorFalse: "#3e3e3e",
    board: "grey",
    text: "white",
    undo: "#282b30",
    left: "#36393e",
    right: "#36393e",
    clear: "#282b30",
    banker: "#dc143c",
    player: "#3c659e",
    search: "#aa6f73",
  },

  light: {
    tabBar: "#473a41",
    background: "white",
    tabFocused: "white",
    tabUnfocused: "grey",
    thumbColorTrue: "white",
    thumbColorFalse: "white",
    trackColorFalse: "#3e3e3e",
    board: "grey",
    text: "black",
    undo: "#66545e",
    left: "#a39193",
    right: "#a39193",
    clear: "#66545e",
    banker: "#dc143c",
    player: "#3c659e",
    search: "#aa6f73",
  },
};

export default colors;
